### ISSUE TITLE
Doesn't Work with Jquery.Inputmask v3.1.33

### ISSUE THREAD

**Issue by mshahrouri** [andr-04/inputmask-multi#10]
when i update the jquery.inputmask to v3.1.33 the pluging stop working correctly.
here is how it looks before entering data 
![1](https://cloud.githubusercontent.com/assets/951528/4782449/e3f9ec78-5cf2-11e4-9f8f-51ffa3ef4d5d.jpg)

and here is how it looks after entering some data 
![2](https://cloud.githubusercontent.com/assets/951528/4782452/fda28ff4-5cf2-11e4-8b9b-485b58c8876d.jpg)

P.S.: it doesn't work with any version above 2.0 of input mask

**Comment by andr-04** [comment]
Да, в настоящий момент плагин работает только с jquery.inputmask v1. Автор этого плагина планировал внедрить поддержку нескольких масок ввода в v2, но я не проверял как это работает. Скорее всего мой плагин, адаптироваться под новую версию jquery.inputmask пока не будет (если его кто-то не адаптирует).

**Comment by Tuning-Soft** [comment]
Он уже внедрил, но браузер тормозит жестоко на русских кодах, стоит вроде как  в планах в версии 3.5

**Comment by klimov-paul** [comment]
See #18

**Comment by andr-04** [comment]
Адаптировал плагин под последнюю существующую версию inputmask. Пользуйтесь.
