### ISSUE TITLE
Забрать значение с маской

### ISSUE THREAD

**Issue by Vaflan** [andr-04/inputmask-multi#12]
Добрый, ковыряю, и не могу найти, каким образом можно забрать из определённого jQuery объекта val() с маской, что бы давалось не цифры, а так же скобки и прочее.
С условием если указано - autoUnmask: true
Спасибо

**Comment by andr-04** [comment]
Это стандартное поведение плагина jquery.inputmask при указанном параметре. Укажите autoUnmask: false.
