### ISSUE TITLE
Great plugin. Is there a way to store the mask formatted input to database field 

### ISSUE THREAD

**Issue by cderees** [andr-04/inputmask-multi#14]
I love the plugin, it works well for me in fields in a form as I input input phone number entries. Is there are way to either store the mask formatted input to a database field or to format when stored input is recalled from a stored database field?

**Comment by andr-04** [comment]
Right now you can't fetch new masks while typing a number. But if you want to store masks in a database you can write a server script which will read masks from the database and generate json file with masks which will be used by inputmask-multi.
