### ISSUE TITLE
Поддержка разработки

### ISSUE THREAD

**Issue by Soul-git** [andr-04/inputmask-multi#19]
Не совсем удобно общаться на английском.
Надеюсь разработка будет поддерживаться в актуальном состоянии для последних версий jquery.inputmask. 
Хотя в наше время уже достаточно мало используют "городские номера" и достаточно вывести в маску сотовый, но многим нравится Ваш вариант надстройки для jquery.inputmask. 
Спасибо.

**Comment by andr-04** [comment]
Если будет потребность в плагине и будут не только открываться issues, но и присылаться pull requests, то поддержка плагина будет продолжаться -- так как это [произошло] (https://github.com/andr-04/inputmask-multi/pull/18) в этот раз с адаптацией к версии 3.x плагина inputmask. Так что, как говорится, you are welcome! =)
