### ISSUE TITLE
isCompleted

### ISSUE THREAD

**Issue by Latrisha** [andr-04/inputmask-multi#25]
Добрый день! Не знала куда вам можно было написать, чтобы задать вопрос. Если я правильно поняла из readme, то опциональный аргумент **mode** можно заюзать, чтобы отследить полностью заполнено поле ввода телефона или нет. Можете привести пример использования этого параметра для проверки заполненности поля? А то не очень поняла, как это использовать. 
Заранее спасибо!

**Comment by andr-04** [comment]
Привет.

Совсем недавно немного изменился способ использования плагина (забыл отразить изменения в Readme) и теперь `'isCompleted'` нужно указывать первым (и единственным) параметром метода `inputmasks`.

Например, если для input с id `#phone` была применена маска ввода, то чтобы узнать текущее состояния _завершённости_ введённого значения нужно выполнить `$('#phone').inputmasks('isCompleted')` -- результатом будет `true` или `false`.

**Comment by kumirska** [comment]
Не очень понятно как и где его заюзать. onMaskChange уже не срабатывает, когда маска определилась ранее, но телефон только что был введен до конца
