### ISSUE TITLE
Использование нескольких полей

### ISSUE THREAD

**Issue by Soul-git** [andr-04/inputmask-multi#26]
Здравствуйте, @andr-04 . 
Возник вопрос. При использовании на странице двух и более полей с использованием вашей надстройки, не удается придать уникальный индекс полю вывода населенного пункта.
К полю маски прикрепляю id поля по типу "#descr_id".

**Comment by andr-04** [comment]
Здравствуйте. Постарался привести пример [тут](https://jsfiddle.net/kp183q11/). От захардкоженных ID при желании можно избавиться, но это не более, чем пример. Надеюсь, я правильно понял что Вы имеете ввиду.
