### ISSUE TITLE
Проблема с вводом номера на мобильных устройствах

### ISSUE THREAD

**Issue by Markeldo** [andr-04/inputmask-multi#30]
Приветствую.
Опишу проблему
Открываю пример в Chrome на мобильном, пытаюсь ввести номер.
Допустим маска +7(___)___-__-__ 
ввожу +7(111)2 и тут курсор перескакивает и встаёт перед двойкой, а не за ней. То же самое, когда дохожу до +7(111)222-3 курсор встаёт перед тройкой. 
То есть, когда вводимый символ становится следующим за ")" или "-", то курсор встаёт перед ним.
Не знаю, понятно ли объяснил, но в любом случае, проще открыть пример на телефоне и попытаться осуществить ввод.
Сможете ли исправить эту ошибку?

P.S.: во встроенном в Android браузере такой проблемы нет.

**Comment by nikolaysigalev** [comment]
Похоже, проблема в Яндекс.Браузере для Андроида. Похожий плагин jquery maskedinput ведет себя так же в этом браузере. Написал им в поддержку.

**Comment by nikolaysigalev** [comment]
Если у поля input указать type="tel", то проблема исчезает

**Comment by Andrikoss** [comment]
nikolaysigalev
Мужик спасибо огромное выручил конкретно
в input стояло type ="text" и при наборе со смартфона глюк
номер набирает и всё сдвигает в право + не работало ограничение и можно было набрать 100500 символов.
Теперь же благодаря твоему совету, даже клавиатуру с цифрами открывает в этом поле.
Конкретно выручил, а то я дубом в этом.
СПАСИБО !!!

**Comment by hey-yo** [comment]
Как вы вообще его подключили? Мне надо только инпут.

**Comment by Markeldo** [comment]
> Как вы вообще его подключили? Мне надо только инпут.

Гляньте на демо-странице, вроде там всё +- понятно: http://andr-04.github.io/inputmask-multi/ru.html
