### ISSUE TITLE
Add austria phone numbers mask

### ISSUE THREAD

**Issue by dmitryuk** [andr-04/inputmask-multi#31]
{ "mask": "+43(677)###-#####", "cc": "AT" },
  { "mask": "+43(681)###-#####", "cc": "AT" },
  { "mask": "+43(688)###-#####", "cc": "AT" },
  { "mask": "+43(699)###-#####", "cc": "AT" },

**Comment by xakzona** [comment]
https://en.wikipedia.org/wiki/List_of_mobile_phone_number_series_by_country

**Comment by dmitryuk** [comment]
abandoned
