### ISSUE TITLE
Актуальность базы

### ISSUE THREAD

**Issue by maximus1010101** [andr-04/inputmask-multi#34]
Здравствуйте,

Масштабирую свой проект на все города России (и СНГ страны).
В связи с тем, что в случае несоответствия кода города одному из предложенных шаблонов, ввод не подходящей цифры отменяется, у меня возник вопрос об актуальности базы городов. Не получится так, что городу добавится новый номер, к моим клиентам будут приходить люди с подобными номерами, а клиенты просто не смогут их номер записать?
Хотелось бы знать, на основании каких данных и как часто обновляется список?
Или как еще можно решить мой вопрос?
Может, есть возможность включить что-то вроде "маски по умолчанию", вроде unknown?

Заранее спасибо за ответ и за отличную разработку! Очень удобная маска, особенно, автоопределение города.

**Comment by andr-04** [comment]
Здравствуйте. База номеров по России бралась из Википедии, для мира -- из [данных](http://www.itu.int/oth/T0202.aspx?parent=T0202) международного союза электросвязи. Данные, к сожалению, обновлялись уже достаточно давно.

Для решения проблемы с отсутствием маски (и невозможностью ввести номер), рекомендуется предусматривать возможность отключения маски ввода -- как это реализовано на демонстрационной [странице](http://andr-04.github.com/inputmask-multi/) проекта. Другой вариант -- да, можно добавить маску по умолчанию в свой список масок. Например, в файл [data/phones-ru.json](https://github.com/andr-04/inputmask-multi/blob/master/data/phones-ru.json) для России можно просто добавить строку, которая и будет маской по умолчанию:
`{ "mask": "+7(###)###-##-##", "region": "", "city": "", "operator": "", "desc": "" }`
Строку можно добавить в любое место (при загрузке весь список сортируется).

**Comment by maximus1010101** [comment]
Спасибо большое за оперативную помощь!
Пока что добавлю маску по умолчанию, а там видно будет. :)
