### ISSUE TITLE
Issue with FF

### ISSUE THREAD

**Issue by sunainasharma** [andr-04/inputmask-multi#5]
The phone masking is working fine in all scenarios except for one. In Firefox, on selection of the text , the masking getting disturbed. I observed the same in your demo application [http://andr-04.github.io/inputmask-multi/en.html] as well It is getting shifted to right hand side. I tried using the new "jquery.inputmask.js [2.x]" from Robert Git repository , but it was breaking the original masking as well. My current version is "1.3.22". You help will be much appreciated.

**Comment by andr-04** [comment]
I have no the issue after update with the latest FF. Try again.
