### ISSUE TITLE
Запрет на удаление кода страны

### ISSUE THREAD

**Issue by 995533** [andr-04/inputmask-multi#9]
Здравствуйте! 
Подскажите, а можно как то сделать что бы код страны нельзя было стереть? 
Я маску страны ставлю при выборе пользователем страны. После того как пользователь переходит к полю заполнения телефона не очень хочу что бы он мог править код страны.

Спасибо.

**Comment by andr-04** [comment]
Скорее всего, оптимальнее эту задачу решать без использования плагина inputmask-multi. Просто используйте json-файл со списком масок и переопределяйте маску в зависимости от выбранной в Combobox'е страны.
